In [41]:
def preprocess_data(data):
    # Drop columns with NaN values
    data = data.dropna(axis=1)

    categorical_columns = ["Materialnummer", "Lieferant OB", "Vertragsposition OB", "Beschaffungsart", "Disponent", "Einkäufer", "Dispolosgröße", "Werk OB", "Warengruppe", "Basiseinheit"]
    numerical_columns = ["Planlieferzeit Vertrag", "Vertrag Fix1", "Vertrag_Fix2", "Gesamtbestand", "Gesamtwert", "Preiseinheit", "WE-Bearbeitungszeit", "Planlieferzeit Mat-Stamm"]

    data[categorical_columns] = data[categorical_columns].astype('category')
    data[numerical_columns] = data[numerical_columns].astype('int64')

    # Select only numeric columns
    processed_data = data[numerical_columns]

    # Normalize features
    #scaler = StandardScaler()
    #processed_data = pd.DataFrame(scaler.fit_transform(processed_data), columns=processed_data.columns)

    return processed_data  

file_path = '../Stammdaten.csv'
df = pd.read_csv(file_path, low_memory=False)
processed_df = preprocess_data(df)

C:\Users\raoul\AppData\Local\Temp\ipykernel_37108\1161721549.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[categorical_columns] = data[categorical_columns].astype('category')
C:\Users\raoul\AppData\Local\Temp\ipykernel_37108\1161721549.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[numerical_columns] = data[numerical_columns].astype('int64')


In [42]:
import numpy as np
from sklearn.cluster import KMeans

def detect_anomalies(data, num_clusters, threshold):
    # Fit KMeans clustering model
    kmeans = KMeans(n_clusters=num_clusters)
    kmeans.fit(data)
    
    # Calculate distances of each point to its nearest cluster center
    distances = kmeans.transform(data)
    
    # Calculate average distance to cluster centers for each point
    avg_distances = np.mean(distances, axis=1)
    
    # Calculate threshold for anomaly detection
    anomaly_threshold = np.percentile(avg_distances, threshold)
    
    # Identify anomalies
    anomalies = data[avg_distances > anomaly_threshold]
    
    return anomalies

anomalies = detect_anomalies(processed_df, num_clusters=5, threshold=95)
print(anomalies)

C:\Users\raoul\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


        Planlieferzeit Vertrag  Vertrag Fix1  Vertrag_Fix2  Gesamtbestand  \
32                           0             0             0              0   
2308                         0             0             0              0   
2309                         0             0             0              0   
2310                         0             0             0              0   
2311                         0             0             0              0   
...                        ...           ...           ...            ...   
184176                       4             4            60        4552510   
185420                     150           150           150          16020   
185490                     112             0             0              0   
185556                      42             0             0              0   
186438                      14            14            84          44060   

        Gesamtwert  Preiseinheit  WE-Bearbeitungszeit  \
32               0

In [43]:
anomalies.to_csv('anomalies.csv', index=False)

In [20]:
processed_df

Planlieferzeit Vertrag  Vertrag Fix1  Vertrag_Fix2  Gesamtbestand  \
0                            0             0             0              0   
1                            0             0             0              0   
2                            0             0             0              0   
3                            0             0             0              0   
4                            0             0             0              0   
...                        ...           ...           ...            ...   
186751                      63             0             0            530   
186752                       4             4            60          67220   
186753                       4             4            60           2000   
186754                       4             4            60          17980   
186755                       4             4            60           1420   

        Gesamtwert  Preiseinheit  WE-Bearbeitungszeit  \
0                0             1                    1   
1                0             1                    1   
2                0             1                    1   
3                0             1                    1   
4                0             1                    1   
...            ...           ...                  ...   
186751      362748           100                    1   
186752      739293           100                    1   
186753       29624           100                    1   
186754        7181           100                    1   
186755        2082           100                    1   

        Planlieferzeit Mat-Stamm  
0                              3  
1                              3  
2                             84  
3                             84  
4                              3  
...                          ...  
186751                        63  
186752                         7  
186753                        21  
186754                         7  
186755                         7  

[186756 rows x 8 columns]

In [36]:
anomalies = detect_anomalies(processed_df, num_clusters=5, threshold=95)

C:\Users\raoul\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [38]:
anomalies

Planlieferzeit Vertrag  Vertrag Fix1  Vertrag_Fix2  Gesamtbestand  \
32                           0             0             0              0   
2308                         0             0             0              0   
2309                         0             0             0              0   
2310                         0             0             0              0   
2311                         0             0             0              0   
...                        ...           ...           ...            ...   
184176                       4             4            60        4552510   
185420                     150           150           150          16020   
185490                     112             0             0              0   
185556                      42             0             0              0   
186438                      14            14            84          44060   

        Gesamtwert  Preiseinheit  WE-Bearbeitungszeit  \
32               0          1000                    1   
2308             0             0                    1   
2309             0             0                    1   
2310             0             0                    1   
2311             0             0                    1   
...            ...           ...                  ...   
184176      111006          1000                    1   
185420   115344675             1                    1   
185490           0             1                    1   
185556           0             1                    1   
186438    29458595             1                    1   

        Planlieferzeit Mat-Stamm  
32                             3  
2308                         999  
2309                         999  
2310                         999  
2311                         999  
...                          ...  
184176                         4  
185420                        84  
185490                       999  
185556                       999  
186438                        84  

[2785 rows x 8 columns]

In [39]:
processed_df

Planlieferzeit Vertrag  Vertrag Fix1  Vertrag_Fix2  Gesamtbestand  \
0                            0             0             0              0   
1                            0             0             0              0   
2                            0             0             0              0   
3                            0             0             0              0   
4                            0             0             0              0   
...                        ...           ...           ...            ...   
186751                      63             0             0            530   
186752                       4             4            60          67220   
186753                       4             4            60           2000   
186754                       4             4            60          17980   
186755                       4             4            60           1420   

        Gesamtwert  Preiseinheit  WE-Bearbeitungszeit  \
0                0             1                    1   
1                0             1                    1   
2                0             1                    1   
3                0             1                    1   
4                0             1                    1   
...            ...           ...                  ...   
186751      362748           100                    1   
186752      739293           100                    1   
186753       29624           100                    1   
186754        7181           100                    1   
186755        2082           100                    1   

        Planlieferzeit Mat-Stamm  
0                              3  
1                              3  
2                             84  
3                             84  
4                              3  
...                          ...  
186751                        63  
186752                         7  
186753                        21  
186754                         7  
186755                         7  

[186756 rows x 8 columns]

In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder


C:\Users\Raoul\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
# Sample categorical data
data = {'category': ['dog', 'cat', 'bird', 'dog', 'cat', 'bird', 'cat', 'bird']}
df = pd.DataFrame(data)

# Apply one-hot encoding
encoder = OneHotEncoder(sparse=False)
one_hot_encoded_data = encoder.fit_transform(df[['category']])
print("One-Hot Encoded Data:")
print(one_hot_encoded_data)


One-Hot Encoded Data:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


C:\Users\Raoul\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [3]:
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(one_hot_encoded_data)
print("Reduced Data:")
print(reduced_data)


Reduced Data:
[[ 4.80740672e-17  9.18558654e-01]
 [ 7.07106781e-01 -3.06186218e-01]
 [-7.07106781e-01 -3.06186218e-01]
 [-6.49174737e-33  9.18558654e-01]
 [ 7.07106781e-01 -3.06186218e-01]
 [-7.07106781e-01 -3.06186218e-01]
 [ 7.07106781e-01 -3.06186218e-01]
 [-7.07106781e-01 -3.06186218e-01]]


In [7]:
file_path = r'C:\Users\Raoul\Desktop\Studium\Semester_10\git_repo\ai-project\algorithms\LOF\sampled_data.csv'
df = pd.read_csv(file_path, low_memory=False)
df.head

<bound method NDFrame.head of       Materialnummer  Lieferant OB    Vertrag OB  Vertragsposition OB  \
0         23884900UB        700000           NaN                    0   
1           00360029        701806  5.500001e+09                   10   
2           04002905        706808           NaN                    0   
3           60022412          1000           NaN                    0   
4         01568000UB        700000           NaN                    0   
...              ...           ...           ...                  ...   
18671       60021775          2000           NaN                    0   
18672       27032205        702225           NaN                    0   
18673       24004600          2000           NaN                    0   
18674     31273400UB          2000           NaN                    0   
18675     01565200UB        700000           NaN                    0   

       Planlieferzeit Vertrag  Vertrag Fix1  Vertrag_Fix2 Beschaffungsart  \
0               